version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e 'js,pug,html' index.js
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
