-- MySQL Script generated by MySQL Workbench
-- Mon Mar  3 15:39:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `bio` VARCHAR(150) NULL,
  `role` VARCHAR(45) NULL,
  `profile_pic` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;

-- Insert dummy users
INSERT INTO `User` (`user_name`, `password`, `phone_number`, `email`, `address`, `bio`, `role`, `profile_pic`)
VALUES
('Alice Johnson', 'password123', 1234567890, 'alice@example.com', '123 Main St, NY', 'Love to travel!', 'Passenger', 'https://yourstorage.com/profile_pics/alice.jpg'),
('Bob Smith', 'pass456', 9876543210, 'bob@example.com', '456 Elm St, LA', 'Driver since 2020', 'Driver', 'https://yourstorage.com/profile_pics/bob.jpg'),
('Charlie Brown', 'charlie789', 1122334455, 'charlie@example.com', '789 Oak St, TX', 'Adventurous soul', 'Passenger', 'https://yourstorage.com/profile_pics/charlie.jpg'),
('David Miller', 'davidpass', 2233445566, 'david@example.com', '321 Pine St, SF', 'Ride-sharing enthusiast', 'Driver', 'https://yourstorage.com/profile_pics/david.jpg'),
('Emma Davis', 'emma123', 3344556677, 'emma@example.com', '654 Cedar St, FL', 'Always on the go!', 'Passenger', 'https://yourstorage.com/profile_pics/emma.jpg'),
('Frank Wilson', 'frankpass', 4455667788, 'frank@example.com', '987 Birch St, WA', 'Long-distance driver', 'Driver', 'https://yourstorage.com/profile_pics/frank.jpg'),
('Grace Thomas', 'grace456', 5566778899, 'grace@example.com', '159 Maple St, CO', 'Loves road trips!', 'Passenger', 'https://yourstorage.com/profile_pics/grace.jpg'),
('Henry Walker', 'henrypass', 6677889900, 'henry@example.com', '753 Redwood St, AZ', 'Ride-sharing pro', 'Driver', 'https://yourstorage.com/profile_pics/henry.jpg'),
('Isabel Scott', 'isabelpass', 7788990011, 'isabel@example.com', '951 Willow St, OR', 'Exploring new cities!', 'Passenger', 'https://yourstorage.com/profile_pics/isabel.jpg'),
('Jack Harris', 'jackpass', 8899001122, 'jack@example.com', '852 Spruce St, NV', 'Nighttime driver', 'Driver', 'https://yourstorage.com/profile_pics/jack.jpg');

-- -----------------------------------------------------
-- Table `mydb`.`ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ride` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ride` (
  `ride_id` INT NOT NULL,
  `driver_id` INT NULL,
  `origin_address` VARCHAR(100) NULL,
  `destination_address` VARCHAR(100) NULL,
  `departure_time` DATETIME NULL,
  `available_seats` INT NULL,
  `ride_details` VARCHAR(150) NULL,
  `ride_pics` VARCHAR(255) NULL,
  PRIMARY KEY (`ride_id`),
  UNIQUE INDEX `ride_id_UNIQUE` (`ride_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '		';

-- Insert dummy rides
INSERT INTO `ride` (`ride_id`, `driver_id`, `origin_address`, `destination_address`, `departure_time`, `available_seats`, `ride_details`, `ride_pics`)
VALUES
(1, 2, '456 Elm St, LA', '789 Oak St, TX', '2025-03-04 10:00:00', 3, 'Morning ride to Texas', 'https://yourstorage.com/ride_pics/ride1.jpg'),
(2, 4, '321 Pine St, SF', '123 Main St, NY', '2025-03-05 15:00:00', 2, 'Cross-country trip', 'https://yourstorage.com/ride_pics/ride2.jpg'),
(3, 6, '987 Birch St, WA', '654 Cedar St, FL', '2025-03-06 08:30:00', 4, 'Road trip across states', 'https://yourstorage.com/ride_pics/ride3.jpg'),
(4, 8, '753 Redwood St, AZ', '951 Willow St, OR', '2025-03-07 12:00:00', 1, 'One-way trip to Oregon', 'https://yourstorage.com/ride_pics/ride4.jpg'),
(5, 10, '852 Spruce St, NV', '159 Maple St, CO', '2025-03-08 14:45:00', 3, 'Evening drive to Colorado', 'https://yourstorage.com/ride_pics/ride5.jpg'),
(6, 2, '789 Oak St, TX', '987 Birch St, WA', '2025-03-09 09:00:00', 2, 'Morning commute', 'https://yourstorage.com/ride_pics/ride6.jpg'),
(7, 4, '321 Pine St, SF', '456 Elm St, LA', '2025-03-10 18:00:00', 4, 'LA trip with stops', 'https://yourstorage.com/ride_pics/ride7.jpg'),
(8, 6, '654 Cedar St, FL', '852 Spruce St, NV', '2025-03-11 11:30:00', 3, 'Scenic drive', 'https://yourstorage.com/ride_pics/ride8.jpg'),
(9, 8, '951 Willow St, OR', '789 Oak St, TX', '2025-03-12 07:15:00', 2, 'Early morning ride', 'https://yourstorage.com/ride_pics/ride9.jpg'),
(10, 10, '159 Maple St, CO', '123 Main St, NY', '2025-03-13 20:00:00', 5, 'Overnight journey', 'https://yourstorage.com/ride_pics/ride10.jpg');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
