name: CI Workflow

on:
  push:
    branches:
      - master
      - release
      - development
  pull_request:
    branches:
      - master
      - release
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Add your deployment script/commands here
          
  staging-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          # Add your staging deployment script/commands here
