
# This is a workflow that is manually triggered to test the docker build

name: Manual workflow for docker

# Controls when the action will run. Triggered by push to deploy branch
on:
  push:
    branches:
      - setup/actions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners to check we are working ok
      - name: check
        run: echo "first job done!"
        # Install checkout the repo
      - uses: actions/checkout@v4
      # get node js
      - uses: actions/setup-node@v4
      - name: check node
        run: node --version
      - name: check dir
        run: ls
      - name: Create the .env file
        run: echo "$" > .env
      - name: Check
        run: cat .env
      - name: Install dependencies
        run: npm install
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose-deploy.yml"


