name: Login Test

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - release
      - master
      
# Single Job Runs Integration Tests
jobs:

  Integration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        - name: Clear cache
          run: |
            rm -rf ~/.npm
            rm -rf node_modules
        - name: check
          run: echo "Installing Dependencies!"
          # Install checkout the repo
        - uses: actions/checkout@v4
          # Setup Node.js
        - uses: actions/setup-node@v4

        - name: Check Node.js Version
          run: node --version
        - name: Check Directory
          run: ls
        - name: Create the .env file
          run: echo "${{ secrets.ENV_FILE }}" > .env
        - name: Check
          run: cat .env
        - name: Install dependencies
          run: npm install
        - uses: hoverkraft-tech/compose-action@v2.0.1
          with:
            compose-file: "./docker-compose.yml"

        - name: List files in the repo
          run: |
              ls -R
          

        - name: get dependencies for tests
          run: sudo apt-get install xvfb
        - name: run the nightwatch tests
          run: xvfb-run --auto-servernum npm test -- --env chrome
